export const eng = {
  reportProblemRide: "Having a problem with your ride? Tell us more.",
  historyNotFound: "No trips found",
  notCodeYet: "No codes yet",
  findFreeScooter: "Find a free scooter",
  questionsAndAnswersFAQ: "Got any questions?",
  questionsAndAnswersFAQ2: "Check FAQ below.",
  locateCloseScooter:
    "Locate the closest available scooter on the map and reserve it.",
  startTheRide: "Start the ride",
  findScooterByDigits:
    "Find your scooter by using the displayed digits in your app and scan the QR code.",
  yourFirstRide: "Your first ride",
  standAndPushScooter:
    "Stand on the scooter and push yourself gently. As soon as the scooter is moving, use the throttle to adjust your speed.",
  breaking: "Braking",
  eachBreakControls:
    "Each brake handle controls one of the wheels. Avoid using single brake to prevent tipping over.",
  useBikeLines: "Use bike lanes!",
  parkingSpot: "Parking spot",
  locateParkingSpot: "Locate a parking spot on map in the app.",
  useKickToPark:
    "Use the kick stand to park the scooter. Ensure you are not blocking anything with the scooter.",
  takeParkedScooterPicture: "Take a photo of your parked scooter.",
  toFindSafety:
    "To find more about the safety of your ride please visit the safety centre in the app.",
  greatJob: "Great job!",
  nowYouReady: "Now you are ready to start your first ride.",
  helmet: "Helmet",
  wearingHelmet: "Wearing a helmet is highly recommended to avoid injuries.",
  ensureScooterSuitableCondition:
    "Ensure that scooter is in suitable condition for a ride. Report the scooter if you believe it is damaged.",
  followRules: "Follow local rules and guidelines",
  ensureNotBreachingRules:
    "Ensure that you are not breaching local rules. Use bike lanes where possible.",
  dontDriveInBadWeather: "Do not drive in bad weather",
  stayAlerted: "Stay alerted",
  ensureYouCanSeeAndHear:
    "Ensure that you can see and hear everything clearly.",
  dontRideIntoxicated: "Do not drive intoxicated",
  km: "km",
  min: "min",
  back: "Back",
  jan: "jan",
  fab: "fab",
  march: "march",
  apr: "apr",
  may: "may",
  june: "june",
  july: "july",
  aug: "aug",
  sep: "sep",
  oct: "oct",
  nov: "nov",
  dec: "dec",
  hour: "h",
  second: "sec",
  signOut: "Sign Out",
  aboutApp: "About app",
  privacyPolicy: "Privacy Policy",
  noRide: "No Ride",
  type: "Type",
  noMessages: "No messages",
  pleaseFillYourPhone: "Please fill your phone",
  clickToSwitchCards: "Click if you want to switch cards",
  clickToSelectCard: "Click on the card you want to select",
  deleteAccount: "Delete my account",
  delete: "Delete",
  deleteAccountPermanently: "Delete your account permanently?",
  youLoseAll:
    "You’ll lose data, history of rides, and everything connected with this app.",
  areYouSure: "Are you sure?",
  areYouSureDeleteCard: "Are you sure to delete card?",
  yes: "Yes",
  no: "No",
  payAgain: "Pay again",
  negativeBalancePay: "Negative balance, please pay.",
  payLastRide: "Please pay for the last ride.",
  maximumCardsExtended: "Maximum cards exceeded.",
  PleaseDeleteOtherCard: "Please delete some other card.",
  transactionError: "Transaction failed, please try again.",
  fillEmail: "Fill in an e-mail",
  negativeBalance: "Neg. balance",
  error: "Error",
  close: "Close",
  allowCamera: "Turn on your camera, please",
  allow: "Allow",
  arrorAddingCard: "Error adding map",
  howParkText:
    "We're committed to keeping the city lean and tidy. We ask you to do the same and verify it by taking a photo of your parking. Don't block pathways, entrances, or bike lanes. Try to park near bike racks or designated parking areas painted on the street. Frequent violation of our parking guidelines we result in an extra charge or even deactivation of your account.",
  inputPhoneNumber: "Input phone number",
  invalidPhoneNumber: "Invalid number",
  continue: "Continue",
  continueWith: "Or continue with",
  terms:
    "If you create a new account, you automatically agree to the Terms of Use and Personal Data Protection",
  enterSms: "Enter the code from the confirmation SMS",
  sentSms: "We sent an SMS confirmation code to the phone number",
  resendCodeIn: "Resend code in",
  resendCode: "Resend code",
  resendSmsCode: "Resend the SMS code",
  requestCall: "Request a call",
  changePhoneNumber: "Change the phone number",
  cannotChangePhone:
    "Your phone number cannot be changed. Contact the Support Team to link your account to another phone number.",
  invalidSms: "Invalid code",
  tellAboutYou: "Tell us something about you",
  whatsYourName: "What is your name?",
  name: "Name",
  surname: "Surname",
  incorrectName: "The name you entered was incorrect",
  incorrectSurName: "The surname you entered was incorrect",
  enterEmail: "Enter your email",
  enterValidEmail: "Please enter a valid email address",
  invalidEmail: "The email you entered is invalid",
  ageSure: "We need to be sure of the age",
  must18: "You can use scooters only when you are 18+ years old",
  able18:
    "You must be at least 18 years old to be able to ride around the town.",
  loading: "Loading",
  lostConnectionLoading: "Check your network connection",
  addPaymentCard: "Add a payment card",
  cardNumber: "Card number",
  expiryDate: "Expiry date",
  cvv: "CVV",
  safetyComesFirst: "Safety comes first",
  noScooterExperience:
    'If you have no experience with electric scooters, we recommend choosing the "Beginner" mode with limited speed.' +
    "\n" +
    "\n" +
    " You can reset this setting to the default 25 km/h at any time in the Safety Center.",
  beginner: "Beginner",
  limitSpeed15: "Limit speed to 15 km/h",
  notNow: "Not now",
  safetyCenter: "Security Center",
  setPreferences: "Set your preferences and get tips for safe driving!",
  scan: "Scan",
  turnOnLocation: "Turn on your location",
  withoutLocation:
    "Without active geolocation functional applications will not be complete",
  iUnderstand: "I understand",
  withoutAccessToFiles: "Without access to files the application will not work",
  freeRide: "Free ride on us!",
  checkPromoForFreeRide: "Check your promo for free ride",
  weAreNotInCity: "Oh, we are not in your city yet!",
  preparingToLaunchServiceInCity:
    "We are just preparing to launch the service in your city. We'll let you know when that changes!",
  becomePartner: "Become a partner",
  connectionLost: "Connection lost. Try again.",
  wantKnowMoreAboutGettingStarted: "I want to know more about getting started",
  safetyTips: "Safety tips",
  learnMoreAboutRoadSafety: "Learn more about road safety",
  learnMoreAboutGettingStarted: "Learn more about getting started",
  localRules: "Local rules",
  learnMoreAboutLocalRequirements: "Learn more about the local requirements",
  privateRide: "Private ride",
  corporateRide: "Corporate ride",
  reserve: "Reserve",
  unlock: "Unlock",
  reserveFor: "Reserve for",
  canReserveScooterForMinutes: "You can reserve a scooter for",
  canReserveScooterForMinutes2:
    "Billing will start as soon as you confirm the reservation.",
  confirmReservation: "Confirm reservation",
  reservationOngoing: "Reservation ongoing",
  cancelReservation: "Cancel reservation",
  reservationCanceled: "Reservation canceled",
  reservationTimedOut: "Reservation timed out",
  reserveAgain: "Reserve again",
  addCard: "Add a card",
  addNewCard: "Add a new card",
  skip: "Skip",
  beforeYourRide: "Before your ride",
  enterYourCardDetails: "Enter your card details to start the ride.",
  drivingInProhibitedZone:
    "You have entered restricted zone. You will not find a parking spot here",
  dangerDriving: "Driving in a prohibited zone",
  prohibitedZone: "Prohibited zone!",
  endRide: "End ride",
  startRide: "Start a ride",
  thisIsParkingZone: "This is parking zone",
  parkingAreaLook:
    "Here you can see what the parking area looks like. Please find one nearby.",
  goParkingZone: "Go to the parking zone!",
  endRideParkingZones:
    "You can only end your ride in a designated parking zones.",
  enterCodeManually: "Enter the code manually",
  scanError: "Scan error. Please try again.",
  enterCodeToUnlock: "Enter the code for unlock",
  scooterReadyEnterCode:
    "Scooter is ready! Enter code) \n(code written on the steering wheel)",
  invalidCode: "Invalid code, please try again.",
  activeRide: "Active ride",
  slowZone: "Slow zone",
  pauseRide: "Pause ride?",
  pauseTemporarilyLock:
    "Pause will temporarily lock the scooter so you can continue your ride later. The pause rate is applied for the duration of the lock.",
  pause: "Pause",
  connectionError: "Connection error",
  parkingZone: "Parking zone",
  PausedRide: "Paused ride",
  continueWithRide: "Continue with ride",
  helpWithRide: "Help with ride",
  checkScooter: "Check the scooter",
  scooterOnKickstand: "The scooter is on the kickstand",
  scooterNotObstruct:
    "The scooter does not obstruct cyclists, entrances, or roads",
  takePictureScooter: "Take a picture of the scooter",
  howPark: "How to park?",
  watchOutParking: "Watchout for your parking!",
  yourRideHasEnded: "Your ride has ended",
  pickUp: "Pick up",
  badRide: "Bad ride",
  goodRide: "Good ride",
  reportProblem: "Report a problem",
  somethingIsWrong:
    "Something is wrong? Let`s look at it together. What is the problem about?",
  parking: "Parking",
  scooter: "Scooter",
  accident: "Accident",
  app: "App",
  contactUs: "Contact us",
  save: "Save",
  parkingProblems: "Parking problems",
  tellMoreAboutIssue: "Tell us a little more about the issue…",
  scooterIsNotHere: "Scooter is not here",
  scooterParkedIncorrectly: "Scooter is parked incorrectly",
  scooterBlockingTraffic: "Scooter is blocking traffic",
  others: "Others",
  scooterNotWorkingTellAboutIssue:
    "Scooter is not working? Tell us a little more about the issue…",
  scooterDamaged: "Scooter is scratched or damaged",
  scooterTechnicalIssue: "Scooter has technical issue",
  scooterTooSlow: "Scooter is too slow",
  appSaysScooterOffline: "App says scooter is offline",
  scooterNotResponding: "Scooter is not responding",
  scooterDoesntStart: "Scooter doesn’t start",
  scooterLayingGround: "Scooter is laying on the ground",
  accidentHappenedTellAboutIssue:
    "Accident happened? Tell us a little more about the issue…",
  iInvolvedInAccident: "I was involved in an accident",
  iDamagedScooter: "I scratched / damaged the scooter",
  appNotWorkTellAboutIssue:
    "The app doesn't work as it should? Tell us a little more about the issue…",
  unableStartTrip: "Unable to start the trip",
  unableEndTrip: "Unable to end the trip",
  myAccountBlocked: "My account is blocked",
  appCrashing: "App is freezing or crashing",
  cantAddCard: "I can’t add the card",
  reportDamage: "Report damage",
  takePictureDamage: "Take a picture of the damage",
  yourComment: "Your comment (required)",
  enterProblemHere: "Enter your problem here…",
  goToProfile: "Go to profile",
  payment: "Payment",
  promoCodes: "Promo codes",
  freeMinutes: "Free minutes",
  minutes: "minutes",
  claim: "Claim",
  history: "History",
  support: "Support",
  partnership: "Partnership",
  rewards: "Rewards",
  personalInfo: "Personal info",
  editYourInfo: "Edit your personal info",
  necessaryInfo: "Necessary info",
  termsService: "Terms of service",
  personalDataProtectionPolicy: "Personal data protection policy",
  aboutApplication: "About application",
  areYouSureAboutChanges: "Are you sure about changes?",
  problemWeCantSolveContactSupport:
    "Do you have a problem that we can't solve in the app? Contact our support",
  questionsAndAnswers: "Questions and answers",
  safety: "Safety",
  chatPhone: "Chat phone",
  howToRide: "How to ride",
  phone: "Phone",
  email: "E-mail",
  chat: "Chat",
  tellProblem: "Tell us what is the problem",
  haveProblemTakeLookFAQ:
    "Do you have a problem or question? Take a look at the FAQ.",
  historyOfRides: "History of rides",
  historyOfPromoCodes: "History of promo codes",
  scooterWillSlowDown:
    "Your scooter will slow down and may stop сompletely. You can’t end your ride here. Please find a parking spot.",
  thankForRegistration:
    "Thank you for your registration. We have a present for you! ",
  welcomeToSvist:
    "Welcome to Svist! Please follow the tutorial to learn how to ride the scooter and get 10 minutes free from us!",
  exit: "Exit",

  send: "Send",
  enterPromoCode: "Enter promo code",
  enterPromoCodeDescription:
    "Enter the code and it will be applied to your next ride.",
  promoCode: "Promo code",
  usedCodes: "Used codes",
  use: "Use",
  congratsPromo: "Congratulations, you’ll get:",
  tripNotYetPaid: "Trip not yet paid",
  supportIssues: "Having any issues?",
  supportIssues2: "Our Support is here for you!",
  Version: "Version",
};
export const ukr = {
  reportProblemRide: "Having a problem with your ride? Tell us more.",
  PleaseDeleteOtherCard: "Please delete unused cards.",
  maximumCardsExtended: "Maximum number of cards reached",
  historyNotFound: "Поїздок не знайдено",
  findFreeScooter: "Знайдіть безкоштовний скутер",
  locateCloseScooter:
    "Знайдіть найближчий доступний скутер на карті та забронюйте його.",
  startTheRide: "Почніть поїздку",
  findScooterByDigits:
    "Знайдіть свій скутер за допомогою відображених цифр у додатку та відскануйте QR-код.",
  yourFirstRide: "Ваша перша поїздка",
  standAndPushScooter:
    "Встаньте на самокат і обережно штовхніться. Як тільки скутер почне рухатися, використовуйте дросель, щоб відрегулювати швидкість.",
  breaking: "Гальмування",
  eachBreakControls:
    "Кожна ручка гальма керує одним із коліс. Уникайте використання одного гальма, щоб запобігти перекиданню.",
  useBikeLines: "Використовуйте велосипедні доріжки!",
  parkingSpot: "Парковка",
  locateParkingSpot: "Знайдіть місце для паркування на карті в додатку.",
  useKickToPark:
    "Використовуйте підставку, щоб припаркувати самокат. Переконайтеся, що ви нічого не блокуєте скутером.",
  takeParkedScooterPicture: "Сфотографуйте свій припаркований скутер.",
  toFindSafety:
    "Щоб дізнатися більше про безпеку вашої поїздки, відвідайте центр безпеки в додатку.",
  greatJob: "Чудова робота!",
  nowYouReady: "Тепер ви готові почати свою першу поїздку.",
  helmet: "Шолом",
  wearingHelmet: "Настійно рекомендується носити шолом, щоб уникнути травм.",
  ensureScooterSuitableCondition:
    "Переконайтеся, що скутер знаходиться в придатному стані для їзди. Повідомте про скутер, якщо вважаєте, що він пошкоджений.",
  followRules: "Дотримуйтеся місцевих правил і вказівок",
  ensureNotBreachingRules:
    "Переконайтеся, що ви не порушуєте місцеві правила. По можливості використовуйте велосипедні доріжки.",
  dontDriveInBadWeather: "Не сідайте за кермо в погану погоду",
  stayAlerted: "Будьте напоготові",
  ensureYouCanSeeAndHear: "Переконайтеся, що ви все чітко бачите і чуєте.",
  dontRideIntoxicated: "Не сідайте за кермо в нетверезому стані",
  km: "км",
  min: "хв",
  back: "Назад",
  jan: "січ.",
  fab: "лют.",
  march: "берез.",
  apr: "квіт.",
  may: "трав.",
  june: "черв.",
  july: "лип.",
  aug: "серп.",
  sep: "верес.",
  oct: "жовт.",
  nov: "лист.",
  dec: "груд.",
  hour: "год",
  second: "сек",
  signOut: "Вийти",
  aboutApp: "Про додаток",
  privacyPolicy: "Політика конфіденційності",
  pleaseFillYourPhone: "Будь ласка, заповніть телефон",
  noRide: "Їздити заборонено",
  type: "Друк",
  notCodeYet: "Ще немає кодів",
  noMessages: "Немає повідомлень",
  clickToSwitchCards: "Натисніть, якщо ви хочете поміняти картки",
  clickToSelectCard: "Оберіть картку, яку ви хочете вибрати",
  payAgain: "Оплатити знову",
  deleteAccount: "Видалити мій акаунт",
  deleteAccountPermanently: "Видалити обліковий запис назавжди?",
  delete: "Видалити",
  youLoseAll:
    "Ви втратите дані, історію поїздок і все, що пов’язано з цією програмою",
  areYouSure: "Ви впевнені?",
  areYouSureDeleteCard: "Ви впевнені, що хочете видалити карту?",
  yes: "Так",
  no: "Ні",
  negativeBalancePay: "Негативний баланс, будь ласка, сплатіть.",
  payLastRide: "Оплатіть, будь ласка, останню поїздку.",
  transactionError: "Помилка транзакції, повторіть спробу.",
  fillEmail: "Заповніть електронну пошту",
  negativeBalance: "Нег. баланс",
  error: "Помилка",
  close: "Закрити",
  allowCamera: "Увімкніть камеру, будь ласка",
  allow: "Дозволити",
  arrorAddingCard: "Помилка додавання карти",
  howParkText:
    "Ми прагнемо підтримувати місто чистим і охайним. Ми просимо вас зробити те ж саме і підтвердити це, сфотографувавши свою парковку. Не блокуйте шляхи, під’їзди чи велосипедні доріжки. Намагайтеся припаркуватися біля стоянок для велосипедів або спеціально відведених паркувальних місць, намальованих на вулиці. Часте порушення наших правил паркування призводить до стягнення додаткової плати або навіть деактивації вашого облікового запису.",
  inputPhoneNumber: "Введіть номер телефону",
  invalidPhoneNumber: "Невірний номер",
  continue: "Продовжити",
  continueWith: "Або продовжити через",
  terms:
    "Якщо ви створюєте новий обліковий запис, ви автоматично погоджуєтеся з Умовами використання та захисту персональних даних",
  enterSms: "Введіть код із SMS підтвердження",
  sentSms: "Ми відправили СМС-код підтвердження на номер",
  resendCodeIn: "Повторно надіслати код через",
  resendCode: "Надіслати код повторно",
  resendSmsCode: "Повторно надіслати SMS-код",
  requestCall: "Надіслати на телефон",
  changePhoneNumber: "Змінити номер телефону",
  cannotChangePhone:
    "Ваш номер телефону не можна змінити. Зв’яжіться зі службою підтримки, щоб зв’язати свій обліковий запис з іншим номером телефону.",
  invalidSms: "Невірний код",
  tellAboutYou: "Розкажіть щось про себе",
  whatsYourName: "Як вас звати?",
  name: "Ім`я",
  surname: "Прізвище",
  incorrectName: "Ім'я, яке ви ввели, було неправильним",
  incorrectSurName: "Ви ввели неправильне прізвище",
  enterEmail: "Введіть адресу електронної пошти",
  enterValidEmail: "Будь ласка, введіть дійсну адресу електронної пошти",
  invalidEmail: "Введена вами електронна адреса недійсна",
  ageSure: "Ми повинні бути впевнені у віці",
  must18: "Користуватися самокатами можна лише з 18 років",
  able18: "Вам має бути принаймні 18 років, щоб мати змогу їздити по місту.",
  loading: "Завантаження",
  lostConnectionLoading: "Перевірте підключення до мережі",
  addPaymentCard: "Додайте платіжну картку",
  cardNumber: "Номер картки",
  expiryDate: "Термін придатності",
  cvv: "CVV",
  safetyComesFirst: "Безпека на першому місці",
  noScooterExperience:
    "Якщо у вас немає досвіду роботи з електросамокатами, рекомендуємо вибрати режим «Початківець» з обмеженою швидкістю." +
    "\n" +
    "\n" +
    " Ви можете будь-коли скинути це налаштування до значення за замовчуванням 25 км/год у Центрі безпеки.",
  beginner: "Початківець",
  limitSpeed15: "Обмеження швидкості до 15 км/год",
  notNow: "Не зараз",
  safetyCenter: "Центр безпеки",
  setPreferences:
    "Визначте свої вподобання та отримуйте поради щодо безпечного водіння!",
  scan: "Сканувати",
  turnOnLocation: "Увімкніть своє місцезнаходження",
  withoutLocation:
    "Без активної геолокації функціональні програми не будуть повноцінними",
  iUnderstand: "Я розумію",
  withoutAccessToFiles: "Без доступу до файлів програма працювати не буде",
  freeRide: "Безкоштовний проїзд!",
  checkPromoForFreeRide: "Перевірте свою акцію на безкоштовну поїздку",
  weAreNotInCity: "О, ми ще не у вашому місті!",
  preparingToLaunchServiceInCity:
    "Ми тільки готуємось запустити послугу у вашому місті. Ми повідомимо вас, коли це зміниться!",
  becomePartner: "Стати партнером",
  connectionLost: "Зв'язок втрачено. Спробуйте знову.",
  wantKnowMoreAboutGettingStarted: "Я хочу дізнатися більше про початок роботи",
  safetyTips: "Поради з безпеки",
  learnMoreAboutRoadSafety: "Дізнайтеся більше про безпеку на дорозі",
  learnMoreAboutGettingStarted: "Дізнайтеся більше про початок роботи",
  localRules: "Місцеві правила",
  learnMoreAboutLocalRequirements: "Дізнайтеся більше про місцеві вимоги",
  privateRide: "Приватна поїздка",
  corporateRide: "Корпоративна поїздка",
  reserve: "Резерв",
  unlock: "Розблокувати",
  reserveFor: "Резерв для",
  canReserveScooterForMinutes: "Ви можете забронювати скутер на",
  canReserveScooterForMinutes2:
    "Оплата почнеться, як тільки ви підтвердите бронювання.",
  confirmReservation: "Підтвердити бронювання",
  reservationOngoing: "Бронювання триває",
  cancelReservation: "Скасувати бронювання",
  reservationCanceled: "Бронювання скасовано",
  reservationTimedOut: "Час очікування бронювання минув",
  reserveAgain: "Резервувати знову",
  addCard: "Додати картку",
  addNewCard: "Додати нову картку",
  skip: "Пропустити",
  beforeYourRide: "Перед поїздкою",
  enterYourCardDetails: "Введіть дані картки, щоб розпочати поїздку.",
  drivingInProhibitedZone:
    "Ви потрапили в зону обмеженого доступу. Тут ви не знайдете місця для паркування",
  dangerDriving: "Проїзд в забороненій зоні",
  prohibitedZone: "Заборонена зона!",
  endRide: "Кінець їзди",
  startRide: "Почати поїздку",
  thisIsParkingZone: "Це зона паркування",
  parkingAreaLook:
    "Тут ви можете побачити, як виглядає паркінг. Будь ласка, знайдіть один поруч.",
  goParkingZone: "Іди в зону паркування!",
  endRideParkingZones:
    "Завершити поїздку можна лише у визначених зонах паркування.",
  enterCodeManually: "Введіть код вручну",
  scanError: "Помилка сканування. Будь ласка спробуйте ще раз.",
  enterCodeToUnlock: "Введіть код для розблокування",
  scooterReadyEnterCode:
    "Скутер готовий! Введіть код) \n(код написаний на кермі)",
  invalidCode: "Невірний код, спробуйте ще раз.",
  activeRide: "Активна їзда",
  slowZone: "Повільна зона",
  pauseRide: "Призупинити поїздку?",
  pauseTemporarilyLock:
    "Пауза тимчасово заблокує самокат, щоб ви могли продовжити поїздку пізніше. Швидкість паузи застосовується на час блокування.",
  pause: "Пауза",
  connectionError: "Помилка з'єднання",
  parkingZone: "Зона паркування",
  PausedRide: "Призупинено поїздку",
  continueWithRide: "Продовжити поїздку",
  helpWithRide: "Допомога з поїздкою",
  checkScooter: "Перевірте скутер",
  scooterOnKickstand: "Самокат стоїть на підставці",
  scooterNotObstruct: "Скутер не заважає велосипедистам, під’їздам чи дорогам",
  takePictureScooter: "Сфотографуйте скутер",
  howPark: "Як паркуватися?",
  watchOutParking: "Слідкуйте за паркуванням!",
  yourRideHasEnded: "Ваша поїздка закінчилася",
  pickUp: "Початок їзди",
  badRide: "Погана їзда",
  goodRide: "Хороша поїздка",
  reportProblem: "Повідомити про проблему",
  somethingIsWrong:
    "Щось не так? Давайте розглянемо це разом. Про що проблема?",
  parking: "Паркінг",
  scooter: "Скутер",
  accident: "ДТП",
  app: "Додаток",
  contactUs: "Зв'яжіться з нами",
  save: "Зберегти",
  parkingProblems: "Проблеми з паркуванням",
  tellMoreAboutIssue: "Розкажіть нам трохи більше про проблему…",
  scooterIsNotHere: "Скутера тут немає",
  scooterParkedIncorrectly: "Скутер неправильно припаркований",
  scooterBlockingTraffic: "Скутер блокує рух",
  others: "Інші",
  scooterNotWorkingTellAboutIssue:
    "Скутер не працює? Розкажіть нам трохи більше про проблему…",
  scooterDamaged: "Скутер подряпаний або пошкоджений",
  scooterTechnicalIssue: "У скутера технічна проблема",
  scooterTooSlow: "Скутер занадто повільний",
  appSaysScooterOffline: "Додаток каже, що скутер офлайн",
  scooterNotResponding: "Скутер не реагує",
  scooterDoesntStart: "Скутер не заводиться",
  scooterLayingGround: "Скутер лежить на землі",
  accidentHappenedTellAboutIssue:
    "Сталася аварія? Розкажіть нам трохи більше про проблему…",
  iInvolvedInAccident: "Я потрапив у ДТП",
  iDamagedScooter: "Я подряпав / пошкодив скутер",
  appNotWorkTellAboutIssue:
    "Додаток не працює належним чином? Розкажіть нам трохи більше про проблему…",
  unableStartTrip: "Неможливо розпочати подорож",
  unableEndTrip: "Не вдалося завершити поїздку",
  myAccountBlocked: "Мій обліковий запис заблоковано",
  appCrashing: "Додаток зависає або виходить з ладу",
  cantAddCard: "Я не можу додати картку",
  reportDamage: "Повідомити про пошкодження",
  takePictureDamage: "Сфотографуйте пошкодження",
  yourComment: "Ваш коментар (обов'язково)",
  enterProblemHere: "Введіть свою проблему тут…",
  goToProfile: "Перейти в профіль",
  payment: "Оплата",
  promoCodes: "Промо коди",
  freeMinutes: "Безкоштовні хвилини",
  minutes: "хвилин",
  claim: "Отримай",
  history: "Історія",
  support: "Підтримка",
  partnership: "Партнерство",
  rewards: "Нагороди",
  personalInfo: "Особиста інформація",
  editYourInfo: "Відредагуйте свою особисту інформацію",
  necessaryInfo: "Необхідна інформація",
  termsService: "Умови обслуговування",
  personalDataProtectionPolicy: "Політика захисту персональних даних",
  aboutApplication: "Про застосування",
  areYouSureAboutChanges: "Ви впевнені в змінах?",
  problemWeCantSolveContactSupport:
    "У вас є проблема, яку ми не можемо вирішити в додатку? Зверніться до нашої служби підтримки",
  questionsAndAnswers: "Питання та відповіді",
  safety: "Безпека",
  chatPhone: "Чат",
  howToRide: "Як їздити",
  phone: "Телефон",
  email: "Пошта",
  chat: "Чат",
  tellProblem: "Розкажіть про проблему",
  haveProblemTakeLookFAQ: "У вас є проблема чи питання? Перегляньте FAQ.",
  historyOfRides: "Історія поїздок",
  historyOfPromoCodes: "Історія промокодів",
  scooterWillSlowDown:
    "Ваш скутер сповільниться і може повністю зупинитися. Ви не можете завершити свою поїздку тут. Будь ласка, знайдіть місце для паркування.",
  thankForRegistration: "Дякуємо за реєстрацію. У нас для вас є подарунок!",
  welcomeToSvist:
    "Ласкаво просимо до Свіст! Будь ласка, дотримуйтесь інструкції, щоб навчитися їздити на скутері та отримати від нас 10 хвилин безкоштовно!",
  exit: "Вихід",

  send: "Відправити",
  enterPromoCode: "Введіть промокод",
  enterPromoCodeDescription:
    "Введіть код, і він буде застосований до вашої наступної поїздки.",
  promoCode: "Промокод",
  usedCodes: "Використані коди",
  use: "Використати",
  congratsPromo: "Вітаємо, ви отримаєте:",
  tripNotYetPaid: "Поїздка ще не оплачена",
  supportIssues: "Виникли проблеми?",
  supportIssues2: "Наша підтримка завжди поруч",
  Version: "Версія",
  questionsAndAnswersFAQ: "У вас є проблема чи питання?",
  questionsAndAnswersFAQ2: "Перегляньте FAQ.",
};
export const sk = {
  reportProblemRide:
    "Niečo nebolo v poriadku? Poďme sa na to spoločne mrknúť. Čoho sa problém týka?",
  PleaseDeleteOtherCard: "Odstráňte prosím nevyužívané karty.",
  maximumCardsExtended: "Dosiahnutý maximálny počet kariet.",
  questionsAndAnswersFAQ: "Máš problém alebo otázku?",
  questionsAndAnswersFAQ2: "Mrkni do FAQ.",
  notCodeYet: "Žiadne kódy",
  historyNotFound: "Nenašli sa žiadne cesty",
  findFreeScooter: "Nájdite si voľný skúter",
  locateCloseScooter:
    "Nájdite na mape najbližší dostupný skúter a zarezervujte si ho.",
  startTheRide: "Začnite jazdu",
  findScooterByDigits:
    "Nájdite svoj skúter pomocou zobrazených číslic v aplikácii a naskenujte QR kód.",
  yourFirstRide: "Vaša prvá jazda",
  standAndPushScooter:
    "Postavte sa na kolobežku a jemne sa zatlačte. Hneď ako sa skúter pohne, pomocou plynu upravte rýchlosť.",
  breaking: "Brzdenie",
  eachBreakControls:
    "Každá brzdová rukoväť ovláda jedno z kolies. Vyhnite sa používaniu jednej brzdy, aby ste zabránili prevráteniu.",
  useBikeLines: "Používajte cyklistické pruhy!",
  parkingSpot: "Parkovacie miesto",
  locateParkingSpot: "Nájdite parkovacie miesto na mape v aplikácii.",
  useKickToPark:
    "Na zaparkovanie skútra použite stojan. Uistite sa, že kolobežkou nič neblokujete.",
  takeParkedScooterPicture: "Odfoťte svoj zaparkovaný skúter.",
  toFindSafety:
    "Ak chcete zistiť viac o bezpečnosti vašej jazdy, navštívte bezpečnostné centrum v aplikácii.",
  greatJob: "Dobrá práca!",
  nowYouReady: "Teraz ste pripravení začať svoju prvú jazdu.",
  helmet: "Prilba",
  wearingHelmet:
    "Dôrazne sa odporúča nosiť prilbu, aby ste sa vyhli zraneniam.",
  ensureScooterSuitableCondition:
    "Uistite sa, že skúter je vo vhodnom stave na jazdu. Nahláste skúter, ak sa domnievate, že je poškodený.",
  followRules: "Dodržiavajte miestne pravidlá a pokyny",
  ensureNotBreachingRules:
    "Uistite sa, že neporušujete miestne pravidlá. Ak je to možné, používajte cyklistické pruhy.",
  dontDriveInBadWeather: "Nejazdite v zlom počasí",
  stayAlerted: "Nejazdite v zlom počasí",
  ensureYouCanSeeAndHear: "Uistite sa, že všetko jasne vidíte a počujete.",
  dontRideIntoxicated: "Nejazdite pod vplyvom alkoholu",
  km: "km",
  min: "min",
  back: "Späť",
  jan: "jan",
  fab: "fab",
  march: "march",
  apr: "apr",
  may: "máj",
  june: "jún",
  july: "júl",
  aug: "aug",
  sep: "sep",
  oct: "okt",
  nov: "nov",
  dec: "dec",
  signOut: "Odhlásit se",
  aboutApp: "O aplikácii",
  privacyPolicy: "Zásady ochrany osobných údajov",
  pleaseFillYourPhone: "Vyplňte prosím svoj telefón",
  noRide: "Žiadna jazda",
  noMessages: "Žiadne správy",
  type: "Písať",
  clickToSwitchCards: "Kliknite, ak chcete zmeniť karty",
  clickToSelectCard: "Kliknite na kartu, ktorú chcete vybrať",
  deleteAccount: "Odstrániť môj účet",
  delete: "Vymazať",
  deleteAccountPermanently: "Chcete natrvalo odstrániť svoj účet?",
  youLoseAll:
    "Stratíte dáta, históriu jázd a všetko, čo súvisí s touto aplikáciou.",
  areYouSure: "Si si istý?",
  areYouSureDeleteCard: "Naozaj chcete odstrániť kartu?",
  yes: "Áno",
  no: "Nie",
  payAgain: "Zaplatiť znova",
  negativeBalancePay: "Záporný zostatok, prosím zaplaťte.",
  payLastRide: "Prosím zaplaťte za posledný výlet.",
  transactionError: "Transakcia zlyhala, zopakujte platbu.",
  fillEmail: "Vyplňte e-mail",
  hour: "hod",
  second: "sek",
  negativeBalance: "Záp. zostatok",
  error: "Chyba",
  close: "Zavrieť",
  allowCamera: "Zapnite fotoaparát, prosím",
  allow: "Povoliť",
  arrorAddingCard: "Chyba pri pridávaní mapy",
  howParkText:
    "Zaviazali sme sa udržiavať mesto čisté a upratané. my požiadajte vás, aby ste urobili to isté a overte si to odfotením vášho parkovania. Neblokujte cesty, vchody alebo cyklistické pruhy. Skúste zaparkovať v blízkosti stojanov na bicykle alebo určených parkovacích plôch namaľovaných na ulici. Časté porušenie našich smerníc o parkovaní bude mať za následok príplatok alebo dokonca deaktiváciu vášho parkovania účtu.",
  inputPhoneNumber: "Zadaj telefónne číslo",
  invalidPhoneNumber: "Неважећи број",
  continue: "Pokračuj",
  continueWith: "Pokračovať s ",
  terms:
    "Pokiaľ si zakladáš nový účet, automaticky súhlasíš s Podmienkami používania a Ochranou osobných údajov",
  enterSms: "Zadaj kód z potvrdzovacej SMS",
  sentSms: "Na telefónne číslo sme ti práve odoslali SMS s potvrdzovacím kódom",
  resendCodeIn: "Znovu zaslať kód o",
  resendCode: "Znovu zaslať kód",
  resendSmsCode: "Znovu zaslať kód pomocou SMS ",
  requestCall: "Požiadať o zavolanie",
  changePhoneNumber: "Upraviť telefónne číslo",
  cannotChangePhone:
    "Vaše telefónne číslo nie je možné zmeniť. Ak chcete priradiť svoj účet k inému telefónnemu číslu, kontaktujte podporu.",
  invalidSms: "Zadaný kód nie je správny",
  tellAboutYou: "Povedz nám niečo o sebe",
  whatsYourName: "Ako sa voláš?",
  name: "Meno",
  surname: "Priezvisko",
  incorrectName: "Chybné meno",
  incorrectSurName: "Zadali ste nesprávne priezvisko",
  enterEmail: "Zadaj svoj e-mail",
  enterValidEmail:
    "Pre úspešné dokončenie registrácie zadaj platnú e-mailovú adresu",
  invalidEmail: "Zadaný e-mail je nesprávný",
  ageSure: "Musíme si byť istí vekom",
  must18: "Kolobežky môžete používať, len ak máte 18+ rokov",
  able18: "Aby si mohol/mohla svišťať mestom, musíš mať aspoň 18 rokov.",
  loading: "Svištííííííííím",
  lostConnectionLoading: "Skontrolujte pripojenie k sieti",
  addPaymentCard: "Vlož platobnú kartu",
  cardNumber: "Číslo karty",
  expiryDate: "Platnosť karty",
  cvv: "CVV kód",
  safetyComesFirst: "Bezpečnosť na prvom mieste",
  noScooterExperience:
    "Ak nemáte skúsenosti s elektrickými kolobežkami, odporúčame zvoliť režim „Začiatočník“ s obmedzenou rýchlosťou.\n\n" +
    "Toto nastavenie môžete kedykoľvek obnoviť na predvolenú hodnotu 25 km/h v Centre bezpečnosti.",
  beginner: "Začiatočník",
  limitSpeed15: "Obmedziť rýchlosť na 15 km/h",
  notNow: "Teraz nie",
  safetyCenter: "Centrum bezpečnosti",
  setPreferences: "Nastav si preferencie a získaj tipy na bezpečnú jazdu!",
  scan: "Naskenovať",
  turnOnLocation: "Zapnúť sledovanie polohy",
  withoutLocation: "Bez aktívnej geolokácie funkčné aplikácie nebudú kompletné",
  iUnderstand: "Rozumiem",
  withoutAccessToFiles: "Zapnúť sledovanie polohy",
  freeRide: "Jazda zadarmo!",
  claim: "Nárokovať si",
  checkPromoForFreeRide: "Čekni sekciu promo kódov pre ďalšie výhody.",
  weAreNotInCity: "Och nie, v tvojom meste ešte nesvištíme! :( ",
  preparingToLaunchServiceInCity:
    "Spustenie služby ešte len pripravujeme. Akonáhle sa to zmení, dáme ti vedieť!",
  becomePartner: "Stať sa partnerom",
  connectionLost: "Pripojenie nesviští :( Skús to znovu.",
  wantKnowMoreAboutGettingStarted: "Chcem vedieť viac o začatí jazdy",
  safetyTips: "Tipy pre bezpečnosť",
  learnMoreAboutRoadSafety: "Dozvedieť sa viac o bezpečnosti na cestách",
  learnMoreAboutGettingStarted: "Dozvedieť sa viac o začatí jazdy",
  localRules: "Miestne pravidlá",
  learnMoreAboutLocalRequirements: "Dozvedieť sa viac o požiadavkách mesta",
  privateRide: "Svištím súkromne ",
  corporateRide: "Svištím na firmu",
  reserve: "Rezervovať",
  unlock: "Odomknúť",
  reserveFor: "Rezervované na",
  canReserveScooterForMinutes: "Kolobežku si môžeš rezervovať na",
  canReserveScooterForMinutes2:
    "Účtovať sa začne akonáhle potvrdíš rezerváciu.",
  confirmReservation: "Potvrdiť rezerváciu",
  reservationOngoing: "Prebieha rezervácia",
  cancelReservation: "Zrušiť rezerváciu",
  reservationCanceled: "Rezervácia zrušená",
  reservationTimedOut: "Čas rezervácie vypršal",
  reserveAgain: "Znova rezervovať",
  addCard: "Pridať kartu",
  addNewCard: "Pridať novú kartu",
  skip: "Preskočiť",
  beforeYourRide: "Predtým než posvištíš",
  enterYourCardDetails: "Ak chceš svišťať, zadaj údaje o svojej karte.",
  drivingInProhibitedZone:
    "Vstúpili ste do zakázanej zóny. Parkovacie miesto tu nenájdete",

  dangerDriving: "Jazda v zakázanej zóne.",
  prohibitedZone: "Zakázaná zóna!",
  endRide: "Ukončiť jazdu",
  startRide: "Začnite jazdu",
  thisIsParkingZone: "Parkovacia zóna",
  parkingAreaLook: "Tu vidíš hranice parkovacej zóny. Dosvišti do nej, prosím!",
  goParkingZone: "Choď do parkovacej zóny! ",
  endRideParkingZones:
    "Jazdu môžeš ukončiť len vo vyznačených parkovacích zónach.",
  enterCodeManually: "Vložiť kód ručne",
  scanError: "Ups, chyba pri skenovaní! Skús to znova.",
  enterCodeToUnlock: "Vlož kód pre odomknutie",
  scooterReadyEnterCode:
    "Kolobežka je pripravená! Vlož kód) \n(kód je napísaný na riadidlách)",
  invalidCode: "Ajaj, neplatný kód! Skús to znova",
  activeRide: "Svištíš!",
  slowZone: "Pomalá zóna",
  pauseRide: "Pozastaviť jazdu?",
  pauseTemporarilyLock:
    "Pozastavenie jazdy dočasne uzamkne kolobežku, takže budeš môcť svišťať neskôr. Poplatok za pauzu je aplikovaná po dobu uzamknutia",
  pause: "Dočasne uzamknúť",
  connectionError: "Pripojenie nesviští",
  parkingZone: "Parkovacia zóna",
  PausedRide: "Pozastavená jazda",
  continueWithRide: "Pokračovať v jazde",
  helpWithRide: "Pomoc pri jazde",
  checkScooter: "Skontroluj kolobežku",
  scooterOnKickstand: "Kolobežka je na stojane",
  scooterNotObstruct:
    "Kolobežka nebráni cyklistom ani chodcom a neprekáža na cestách.",
  takePictureScooter: "Vyfoť kolobežku",
  howPark: "Ako zaparkovať? ",
  watchOutParking: "Pozor na to ako parkuješ!",
  yourRideHasEnded: "Vaša cesta sa skončila",
  pickUp: "Vyzdvihnutie",
  badRide: "Nič moc jazda ",
  goodRide: "Cool jazda ",
  reportProblem: "Nahlásiť problém",
  somethingIsWrong:
    "Niečo nebolo v poriadku? Poďme sa na to spoločne pozrieť. Čoho sa problém týka?",
  parking: "Parkovanie",
  scooter: "Kolobežka",
  accident: "Nehoda",
  app: "Aplikácia",
  contactUs: "Kontaktuj nás",
  save: "Uložiť",
  parkingProblems: "Problémy s parkovaním",
  tellMoreAboutIssue: "Povedz nám o probléme trochu viac…",
  scooterIsNotHere: "Kolobežka tu nie je",
  scooterParkedIncorrectly: "Kolobežka je zaparkovaná nesprávne",
  scooterBlockingTraffic: "Kolobežka blokuje premávku",
  others: "Iné",
  scooterNotWorkingTellAboutIssue:
    "Kolobežka nesviští? Povedz nám o probléme trochu viac…",
  scooterDamaged: "Kolobežka je poškriabaná alebo poškodená",
  scooterTechnicalIssue: "Kolobežka má technický problém",
  scooterTooSlow: "Kolobežka je príliš pomalá",
  appSaysScooterOffline: "Aplikácia hovorí/ukazuje, že je kolobežka offline",
  scooterNotResponding: "Kolobežka nereaguje",
  scooterDoesntStart: "Kolobežka nechce naštartovať",
  scooterLayingGround: "Kolobežka leží na zemi",
  accidentHappenedTellAboutIssue:
    "Došlo k zrážke? Povedz nám o probléme trochu viac…",
  iInvolvedInAccident: "Bol/a som účastníkom nehody",
  iDamagedScooter: "Poškriabal/a som alebo poškodil/a kolobežku",
  appNotWorkTellAboutIssue:
    "Appka nesviští ako by mala? Povedz nám o probléme trochu viac…",
  unableStartTrip: "Nejde začať jazdu",
  unableEndTrip: "Nejde ukončiť jazdu",
  myAccountBlocked: "Môj účet je zablokovaný",
  appCrashing: "Appka zamŕza alebo vypadáva",
  cantAddCard: "Nemôžem pridať kartu",
  reportDamage: "Nahlásiť poškodenie",
  takePictureDamage: "Odfotiť poškodenie",
  yourComment: "Tvoj komentár",
  enterProblemHere: "Tu zadajte svoj problém…",
  goToProfile: "Prejsť na profil",
  payment: "Platba",
  promoCodes: "Promo kódy",
  freeMinutes: "Voľné minúty",
  minutes: "minút",
  history: "História",
  support: "Podpora",
  partnership: "Spolupráca",
  rewards: "Odmeny",
  personalInfo: "Osobné údaje",
  editYourInfo: "Upravte svoje osobné údaje",
  necessaryInfo: "Potrebné informácie",
  termsService: "Podmienky služby",
  personalDataProtectionPolicy: "Zásady ochrany osobných údajov",
  aboutApplication: "O aplikácii",
  areYouSureAboutChanges: "Si si istý/á zmenami?",
  problemWeCantSolveContactSupport:
    "Máš problém, ktorý v appke nevyriešime? Obrať sa na našu podporu. Pomôžeme ti skôr než stihneš povedať “SVIŠŤ”!",
  questionsAndAnswers: "Otázky a odpovede",
  safety: "Bezpečnosť",
  howToRide: "Ako jazdiť",
  chatPhone: "Telefón na chat",
  phone: "Telefón",
  email: "E-mail",
  chat: "Chat",
  tellProblem: "Povedz nám, čo sa deje!",
  haveProblemTakeLookFAQ: "Máš problém alebo otázku? Mrkni do FAQ.",
  historyOfRides: "História jázd",
  historyOfPromoCodes: "História promo kódov",
  scooterWillSlowDown:
    "Vaša kolobežka sa spomalí a môže sa úplne zastaviť. Tu nemôžete svoju jazdu ukončiť. Nájdite parkovacie miesto.",
  thankForRegistration: "Ďakujeme za registráciu. Máme pre vás darček!",
  welcomeToSvist:
    "Vitajte vo Svist! Postupujte podľa návodu, aby ste sa naučili jazdiť na kolobežke a získajte od nás 10 minút zadarmo!",
  exit: "Výstup",

  send: "Odoslať",
  enterPromoCode: "Zadajte propagačný kód",
  enterPromoCodeDescription: "Zadajte kód a použije sa pri vašej ďalšej jazde.",
  promoCode: "Promo kód",
  usedCodes: "Použité kódy",
  use: "Použitie",
  congratsPromo: "Gratulujeme, dostanete:",
  tripNotYetPaid: "Cesta ešte nie je zaplatená",
  supportIssues: "Máš problém, ktorý v appke nevyriešime?",
  supportIssues2:
    "Obráť sa na našu podporu. Pomôžeme ti skôr než stihneš povedať “SVIŠŤ”!",
  Version: "Verzia",
};
